<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NeuralPad.Core\NeuralPad.Core.csproj" />
    <PackageReference Include="DevExpress.Wpf.Core" Version="26.1.*" />
    <PackageReference Include="DevExpress.Wpf.Docking" Version="26.1.*" />
    <PackageReference Include="DevExpress.Wpf.PropertyGrid" Version="26.1.*" />
    <PackageReference Include="DevExpress.Wpf.Grid" Version="26.1.*" />
    <PackageReference Include="DevExpress.Wpf.Charts" Version="26.1.*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.9.0" />
  </ItemGroup>
</Project>